use anyhow::Result;
use winsafe::HKEY;

use w11boost::{set_dword, set_string};

const REGISTRY_DWORDS: &[(&str, &str, &str, u32)] = &[
        // Firefox telemetry (HKLM)
        ("HKLM", r"Software\Policies\Mozilla\Firefox", "DisableTelemetry", 1),
        // Firefox telemetry (HKCU)
        ("HKCU", r"Software\Policies\Mozilla\Firefox", "DisableTelemetry", 1),
        // Office 365 telemetry
        (
                "HKCU",
                r"Software\Policies\Microsoft\office\16.0\common\privacy",
                "SendTelemetry",
                3,
        ),
];

pub const ENV_VARS: &[(&str, &str)] = &[
        // === .NET / Microsoft ===
        ("DOTNET_CLI_TELEMETRY_OPTOUT", "1"),
        ("DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT", "1"),
        ("DOTNET_SVCUTIL_TELEMETRY_OPTOUT", "1"),
        ("MLDOTNET_CLI_TELEMETRY_OPTOUT", "1"),
        ("MSSQL_CLI_TELEMETRY_OPTOUT", "1"),
        ("VSTEST_TELEMETRY_OPTEDIN", "0"),
        ("POWERSHELL_TELEMETRY_OPTOUT", "1"),
        ("AZURE_CORE_COLLECT_TELEMETRY", "0"),
        ("AZURE_DEV_COLLECT_TELEMETRY", "no"),
        ("AZUREML_SDKV2_TELEMETRY_OPTOUT", "1"),
        ("FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT", "1"),
        // === Node.js / JavaScript Ecosystem ===
        ("NEXT_TELEMETRY_DISABLED", "1"),
        ("NUXT_TELEMETRY_DISABLED", "1"),
        ("GATSBY_TELEMETRY_DISABLED", "1"),
        ("NG_CLI_ANALYTICS", "false"),
        ("NG_CLI_ANALYTICS_SHARE", "false"),
        ("ASTRO_TELEMETRY_DISABLED", "1"),
        ("STORYBOOK_DISABLE_TELEMETRY", "1"),
        ("REDWOOD_DISABLE_TELEMETRY", "1"),
        ("YARN_ENABLE_TELEMETRY", "0"),
        ("HINT_TELEMETRY", "off"),
        ("VUEDX_TELEMETRY", "off"),
        ("STRAPI_TELEMETRY_DISABLED", "true"),
        ("SLS_TELEMETRY_DISABLED", "1"),
        ("SLS_TRACKING_DISABLED", "1"),
        ("CALCOM_TELEMETRY_DISABLED", "1"),
        ("SKU_TELEMETRY", "false"),
        ("EMBER_CLI_ANALYTICS", "false"),
        ("CAPACITOR_TELEMETRY", "false"),
        ("CARBON_TELEMETRY_DISABLED", "1"),
        // === Python Ecosystem ===
        ("DAGSTER_DISABLE_TELEMETRY", "1"),
        ("FEAST_TELEMETRY", "False"),
        ("MELTANO_DISABLE_TRACKING", "True"),
        ("RASA_TELEMETRY_ENABLED", "false"),
        ("HAMILTON_TELEMETRY_ENABLED", "false"),
        ("HF_HUB_DISABLE_TELEMETRY", "1"),
        ("GRADIO_ANALYTICS_ENABLED", "False"),
        ("RAGAS_DO_NOT_TRACK", "1"),
        ("OPENLLM_DO_NOT_TRACK", "1"),
        ("FLWR_TELEMETRY_ENABLED", "0"),
        ("STREAMLIT_TELEMETRY_OPT_OUT", "1"),
        ("WHYLOGS_NO_ANALYTICS", "true"),
        ("JINA_OPTOUT_TELEMETRY", "1"),
        ("SCHEMATHESIS_TELEMETRY", "false"),
        ("DBT_SEND_ANONYMOUS_USAGE_STATS", "false"),
        // === DevOps / Infrastructure ===
        ("TERRAFORM_TELEMETRY", "0"),
        ("CHECKPOINT_DISABLE", "1"),
        ("VAGRANT_CHECKPOINT_DISABLE", "1"),
        ("PACKER_CHECKPOINT_DISABLE", "1"),
        ("CONSUL_CHECKPOINT_DISABLE", "1"),
        ("ARM_DISABLE_TERRAFORM_PARTNER_ID", "true"),
        ("CHEF_TELEMETRY_OPT_OUT", "1"),
        ("AUTOMATEDLAB_TELEMETRY_OPTOUT", "1"),
        ("NUKE_TELEMETRY_OPTOUT", "1"),
        ("PNPPOWERSHELL_DISABLETELEMETRY", "true"),
        ("EARTHLY_DISABLE_ANALYTICS", "1"),
        ("WERF_TELEMETRY", "0"),
        ("SCOUT_DISABLE", "1"),
        ("INFRACOST_SELF_HOSTED_TELEMETRY", "false"),
        ("BATECT_ENABLE_TELEMETRY", "false"),
        ("DECK_ANALYTICS", "off"),
        ("DO_NOT_TRACK", "1"),
        ("KICS_COLLECT_TELEMETRY", "0"),
        ("DISABLE_CRASH_REPORT", "1"),
        ("CIRCLECI_CLI_TELEMETRY_OPTOUT", "1"),
        ("CODER_TELEMETRY_ENABLE", "false"),
        // === Cloud Providers ===
        ("SAM_CLI_TELEMETRY", "0"),
        ("CLOUDSDK_CORE_DISABLE_USAGE_REPORTING", "true"),
        ("HOOKDECK_CLI_TELEMETRY_OPTOUT", "1"),
        ("STRIPE_CLI_TELEMETRY_OPTOUT", "1"),
        ("F5_ALLOW_TELEMETRY", "false"),
        ("TEEM_DISABLE", "true"),
        ("MSLAB_TELEMETRY_LEVEL", "None"),
        // === Database Tools ===
        ("INFLUXD_REPORTING_DISABLED", "true"),
        ("QUILT_DISABLE_USAGE_METRICS", "True"),
        ("QDRANT__TELEMETRY_DISABLED", "true"),
        ("MONGODB_ATLAS_TELEMETRY_ENABLE", "false"),
        ("FERRETDB_TELEMETRY", "disable"),
        ("CUBESTORE_TELEMETRY", "false"),
        ("CUBEJS_TELEMETRY", "false"),
        ("EVENTSTORE_TELEMETRY_OPTOUT", "1"),
        // === Shells & CLI Tools ===
        ("HOMEBREW_NO_ANALYTICS", "1"),
        ("CHOOSENIM_NO_ANALYTICS", "1"),
        ("COCOAPODS_DISABLE_STATS", "true"),
        ("ARDUINO_METRICS_ENABLED", "false"),
        ("ROCKSET_CLI_TELEMETRY_OPTOUT", "1"),
        ("APOLLO_TELEMETRY_DISABLED", "1"),
        ("SFDX_DISABLE_TELEMETRY", "true"),
        ("SF_DISABLE_TELEMETRY", "true"),
        ("SALTO_TELEMETRY_DISABLE", "1"),
        ("BF_CLI_TELEMETRY", "false"),
        ("MOBILE_CENTER_TELEMETRY", "off"),
        ("APPCD_TELEMETRY", "0"),
        ("TUIST_STATS_OPT_OUT", "1"),
        ("GOTELEMETRY", "off"),
        // === AI/ML Tools ===
        ("RAY_USAGE_STATS_ENABLED", "0"),
        ("APTOS_DISABLE_TELEMETRY", "1"),
        ("SPEEDSTER_DISABLE_TELEMETRY", "1"),
        ("DISABLE_DEEPCHECKS_ANONYMOUS_TELEMETRY", "True"),
        ("DISABLE_DCS_ANONYMOUS_TELEMETRY", "1"),
        ("DACFX_TELEMETRY_OPTOUT", "1"),
        // === Web Frameworks ===
        ("REACT_APP_WEBINY_TELEMETRY", "false"),
        ("PRISMA_TELEMETRY", "false"),
        ("ORYX_DISABLE_TELEMETRY", "true"),
        ("SQA_OPT_OUT", "true"),
        ("HASURA_GRAPHQL_ENABLE_TELEMETRY", "false"),
        ("MEILI_NO_ANALYTICS", "true"),
        ("NOCODB_TELEMETRY", "false"),
        ("NC_DISABLE_TELE", "1"),
        ("PROSE_TELEMETRY_OPTOUT", "1"),
        ("RESTLER_TELEMETRY_OPTOUT", "1"),
        ("PROJECTOR_TELEMETRY_ENABLED", "0"),
        ("MEDUSA_DISABLE_TELEMETRY", "1"),
        ("TELEMETRY_ENABLED", "0"),
        // === Build Tools ===
        ("ALIBUILD_NO_ANALYTICS", "1"),
        ("FASTLANE_OPT_OUT_USAGE", "YES"),
        ("COVERITY_CLI_TELEMETRY_OPTOUT", "1"),
        ("GRADLE_ENTERPRISE_ANALYTICS_DISABLE", "1"),
        ("LOST_PIXEL_DISABLE_TELEMETRY", "1"),
        // === Container & Kubernetes ===
        ("DOCKER_SCAN_SUGGEST", "false"),
        ("KUBEAPT_DISABLE_TELEMETRY", "1"),
        ("DASH_DISABLE_TELEMETRY", "1"),
        ("DAGGER_TELEMETRY_DISABLE", "1"),
        ("NEONKUBE_DISABLE_TELEMETRY", "true"),
        ("OTTERIZE_TELEMETRY_ENABLED", "false"),
        ("PORTER_TELEMETRY_ENABLED", "false"),
        ("PREEVY_DISABLE_TELEMETRY", "1"),
        // === Testing Tools ===
        ("REPORTPORTAL_CLIENT_JS_NO_ANALYTICS", "true"),
        ("AGENT_NO_ANALYTICS", "1"),
        ("BUGGER_OFF", "1"),
        ("SUGGESTIONS_OPT_OUT", "1"),
        ("DA_TEST_DISABLE_TELEMETRY", "1"),
        // === Misc Developer Tools ===
        ("ET_NO_TELEMETRY", "1"),
        ("LYNX_ANALYTICS", "0"),
        ("DISABLE_QUICKWIT_TELEMETRY", "1"),
        ("AUTOMAGICA_NO_TELEMETRY", "1"),
        ("NETDATA_ANONYMOUS_STATISTICS", "0"),
        ("TILT_TELEMETRY", "0"),
        ("MM_LOGSETTINGS_ENABLEDIAGNOSTICS", "false"),
        ("LS_METRICS_HOST_ENABLED", "0"),
        ("PANTS_ANONYMOUS_TELEMETRY_ENABLED", "false"),
        ("FLAGSMITH_TELEMETRY_DISABLED", "1"),
        ("ONE_CODEX_NO_TELEMETRY", "True"),
        ("AITOOLSVSCODE_DISABLETELEMETRY", "1"),
        ("IG_PRO_OPT_OUT", "YES"),
        ("REDOCLY_TELEMETRY", "off"),
        ("HARDHAT_DISABLE_TELEMETRY_PROMPT", "1"),
        ("TAOS_TELEMETRY_REPORTING", "0"),
        ("MF_SEND_TELEMETRY", "false"),
        ("TELEPORT_ANONYMOUS_TELEMETRY", "0"),
        ("TUNNELMOLE_TELEMETRY", "0"),
        ("WG_TELEMETRY_DISABLED", "1"),
        ("ANYCABLE_DISABLE_TELEMETRY", "1"),
        ("RIG_TELEMETRY_ENABLED", "false"),
        ("ELECTRIC_TELEMETRY", "false"),
        ("SNOWFLAKE_DISABLE_TELEMETRY", "1"),
        ("OASDIFF_NO_TELEMETRY", "1"),
        ("EMQX_TELEMETRY__ENABLE", "false"),
        ("KARATE_TELEMETRY", "false"),
        ("CONJUR_TELEMETRY_ENABLED", "false"),
        ("CONJUR_FEATURE_TELEMETRY_ENDPOINT_ENABLED", "false"),
        ("TAIGA_TELEMETRY_ENABLED", "false"),
        ("FA_NOTRACK", "true"),
        ("INFISICAL_TELEMETRY_ENABLED", "false"),
        ("BOXYHQ_NO_ANALYTICS", "1"),
        ("ADSERVER_DO_NOT_TRACK", "1"),
        ("UPSTASH_DISABLE_TELEMETRY", "1"),
        ("BITRISE_ANALYTICS_DISABLED", "1"),
        ("AKITA_DISABLE_TELEMETRY", "1"),
        ("REDGATE_DISABLE_TELEMETRY", "1"),
        ("FLAKE_CHECKER_NO_TELEMETRY", "1"),
        ("PP_TOOLS_TELEMETRY_OPTOUT", "1"),
        ("PIPELINES_TELEMETRY_OPT_OUT", "1"),
        ("PATCHER_TELEMETRY_OPT_OUT", "1"),
        ("RETRACED_NO_TELEMETRY", "1"),
        ("KEYSTONE_TELEMETRY_DISABLED", "1"),
        ("STP_DISABLE_TELEMETRY", "1"),
        ("USAGE_DISABLE", "1"),
        ("ANALYTICS_DISABLED", "1"),
        ("ORBIT_TELEMETRY_DISABLED", "1"),
        ("FAL_STATS_ENABLED", "false"),
        ("LEON_TELEMETRY", "false"),
        ("AP_TELEMETRY_ENABLED", "false"),
        ("ITERATIVE_DO_NOT_TRACK", "1"),
        ("DVC_NO_ANALYTICS", "1"),
        ("BALENARC_NO_ANALYTICS", "1"),
        ("DOZZLE_NO_ANALYTICS", "1"),
        ("RIFF_DISABLE_TELEMETRY", "true"),
        ("VISTRAILS_USAGE_STATS", "off"),
        ("MOMENTUM_TELEMETRY_LEVEL", "silent"),
        // === Claude Code ===
        ("DISABLE_NON_ESSENTIAL_MODEL_CALLS", "1"),
        ("CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY", "1"),
        ("DISABLE_ERROR_REPORTING", "1"),
        // === Generic / Cross-Platform ===
        ("CI", "true"),
        ("DISABLE_TELEMETRY", "1"),
        ("DISABLETELEMETRY", "true"),
        ("NO_TELEMETRY", "1"),
        ("TELEMETRY_DISABLED", "1"),
        ("COLLECT_TELEMETRY", "0"),
        ("ALLOW_UI_ANALYTICS", "false"),
        ("DISABLE_ANALYTICS", "true"),
        ("ANALYTICS", "no"),
        // === Homebrew Extra ===
        ("HOMEBREW_NO_ANALYTICS_THIS_RUN", "1"),
];

pub fn run() -> Result<()>
{
        let hkcu = HKEY::CURRENT_USER;
        let hklm = HKEY::LOCAL_MACHINE;
        let env_path = r"Environment";

        // Set environment variables
        for (var_name, value) in ENV_VARS {
                set_string(&hkcu, env_path, var_name, value)?;
        }

        // Set registry DWORD values
        for (hkey_str, subkey, value_name, value) in REGISTRY_DWORDS {
                let hkey = if *hkey_str == "HKLM" { &hklm } else { &hkcu };
                set_dword(hkey, subkey, value_name, *value)?;
        }

        Ok(())
}
