== 2.0 -> ???
[%collapsible]
====
* Port TuneUp11 to C++ using the Windows UI API.
- C++ is nicer to work with; can be as simple as PowerShell for scripting purposes, but has higher flexibility and performance.
- GUI is better than editing a file in terms of usability.
** Converting to a GUI would bring more attention to this project as well.
- Easy to exclude from anti-malware without having to disable it entirely.
** Code Signing is ~$50 a year, which would help with reporting to anti-malware companies that TuneUp11 is a false positive.
** EV Code Signing would solve the detection issues, but costs ~$200 USD a year, and it's likely this program wouldn't pass since Microsoft verifies it manually.
====

== 1.3.0 -> 23 October 2022
* Removed `Drivers.reg`; it breaks Windows 11 build 22621.675 to disable 'ahcache'.
* Removed disabling mitigations; not worth a few extra percentage increase in FPS for specific games, to then put your data in constant jeopardy. One of the more important ones being Memory Integrity, which prevents vulnerable drivers from being loaded, which would bypass anti-virus software entirely.

== 1.2.0 -> 25 September 2022
* `main.ps1`, `TuneUp11.bat`, `Backup_Registry.bat`, `W11_LTSC_2022.bat`, 'Install_Xbox_Minimal.bat', 'IXM.ps1', 'WL22.ps1'
- Improved Administrator error messages and/or checks.

* `README.adoc`
- Stop recommending O&O ShutUp10++.
- Add shoutout section for programs/scripts I looked at to improve TuneUp11.

* `main.ps1`
- Specifically set System mitigations for `mitigations=0` through PowerShell instead of importing an XML file.
- Improve setting the following: `-ApplicationLaunchPrefetching`, `-ApplicationPreLaunch`, `-MemoryCompression`.
- Start enabling Boot UX; helps with troubleshooting for minimal startup time impact.
- Disable Page Combining to trade higher MEM usage for less CPU usage.
- Ensure SuperFetch/SysMain is enabled; explanation located in `Non-GPO Registry\mistake_corrections.reg`
- Improved `Non-GPO Registry\disable_typing_insights.reg` by also disabling text prediction for hardware keyboards.
- Disable telemetry for:
** Visual Studio
- Disable "Application Compatibility Cache" and the "BEEP" driver.
- Ensure the "ReadyBoost" driver is enabled to prevent the `INACCESSIBLE_BOOT_DEVICE` BSOD.
- Ensure the "LUA File Virtualization Filter" driver is enabled to keep User Account Control (UAC) working.

== 1.1.0 -> 22 September 2022
* `main.ps1` 
- Install Process Lasso Free by default; option is `process_lasso`.
** Also applies the fix for the "Bitsum Highest Performance" Power Plan being unable to apply.
- Set `geolocation` default to 1.
- Fixed `reset_network_interface_settings=1` running too late, which removed previous networking tweaks by TuneUp11.
- Renamed:
** `no_ethernet_power_saving` -> `ethernet_power_saving`.
** `no_audio_reduction` -> `audio_reduction`.
*** Can also now partially revert `audio_reduction=0` (`no_audio_reduction=1` previously) by using `audio_reduction=0`.
** `no_game_dvr` -> `game_dvr`.
** `no_mitigations` -> `mitigations`.

* `Backup_Registry.bat`
- Added an Administrator check.

* Added `Install_Xbox_Minimal.bat` and `W11_LTSC_2022.bat` to easily run their PowerShell scripts with Administrator.
** Why: there's no 'run as Administrator' for PowerShell built into Windows' context menu.

* `WL22.ps1`
- Fixed a regression: `--accept-package-agreements` don't exist for `winget uninstall`.

* Software -> Programs for naming, since that's what Microsoft refers to them as.

== 1.0.2 -> 20 September 2022
* `TuneUp11.bat`, `Install_Xbox_Minimal.ps1`, `W11_LTSC_2022.ps1`
- Bypass license & source agreements for winget.

* `Install_Xbox_Minimal.ps1`, `W11_LTSC_2022.ps1`
- Check for Administrator (Elevated CurrentUser).

== 1.0.1 -> 20 September 2022
* `TuneUp11.bat`
- Speed up Administrator check in `TuneUp11.bat`.

* `main.ps1`
- Use highest permission levels by default with NSudo. Programs not compatible with this are manually ran with Elevated CurrentUser instead of TrustedInstaller.
