:experimental:
:imagesdir: imgs/
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Learning resources used
[%collapsible]
====

. https://archive.org/details/windows-internals-part1-7th/mode/2up
** https://github.com/zodiacon/WindowsInternals
. https://www.microsoftpressstore.com/store/windows-internals-part-2-9780135462409
** This can be viewed for free from link:https://en.wikipedia.org/wiki/Z-Library[Z-Library].
====

== Notes
* Does not overwrite user preferences that decrease privacy, except for those with a noticeable performance impact.
** It's assumed third-party tools do this job better, and not everyone wants to disable features that have privacy concerns.

* Gets rid of some of the auto-piloting that accumulatively is intensive on system resources, such as the link:https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.ApplicationCompatibility::AppCompatTurnOffEngine[Application Compatibility Engine].
** For ACE being off specifically, you would manually specify to run a legacy application in compatibility mode (likely for Windows XP).

* Fixes fuck-ups made by other optimizers and modded Windows ISOs.

* Only Windows 10 LTSC 2022 and newer are tested. 
** Older versions of Windows are worse in terms of stability, which also includes Windows 7.

.Developer notes
[%collapsible]
====

* `reg.exe` is used instead of `reg` incase the system environment variables are misconfigured, same applies to anything else with `.exe` appended to its end.

* `reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\EXAMPLE" /v "Start" /t REG_DWORD /d 4 /f` is preferred over using `sc.exe config EXAMPLE start=disabled` since Windows rejects this request depending on the service.

* MMCSS (Multimedia Class Scheduler) doesn't exist in Windows 10 LTSC 2022 and newer.

* Registry keys usually don't self-regenerate themselves if their key doesn't exist.
** If the purpose is to revert back to defaults, manually set the default value instead.
====

== Requirements
. Windows has to be activated for some changes, use your license key, or use either link:https://github.com/abbodi1406/KMS_VL_ALL_AIO[abbodi1406's KMS_VL_ALL_AIO] or massgravel's link:https://github.com/massgravel/Microsoft-Activation-Scripts[Microsoft Activation Scripts].

. W11Boost.bat's `replace_windows_search=1` requires `winget`.
** For Windows 10 LTSC 2019 or 2022, run in Command Prompt as Administrator to install `winget`:
*** `wsreset -i`
*** After that command is completed, reboot.
*** Open the Microsoft Store, then install "App Installer" through it.

** For Windows 10 LTSB 2016, install the Microsoft Store (provides the AppX installer, which provides `winget`) link:https://forums.mydigitallife.net/threads/guide-add-store-to-windows-10-enterprises-sku-ltsb-ltsc.70741/page-18#post-1388330[here].


== Instructions
. link:https://github.com/nermur/W11Boost/archive/refs/heads/master.zip[Download W11Boost], then extract it.
. Configure the options located inside `W11Boost.bat`, then run it as Administrator.

NOTE: Disable all anti-virus software before running `W11Boost.bat`.

== Recommendations

=== Tweaks
. Enable the following options in your motherboard's BIOS:
** I/O APIC (IOAPIC 24-119 Entries)
** Above 4G Decoding
** Resizable BAR
*** NOTE: If Windows cannot boot (likely from using MBR instead of GPT), disable Resizable BAR.
** HPET (High Precision Event Timer)

. Disable the following options in your motherboard's BIOS:
** XHCI Hands Off
** USB Legacy
*** link:https://techcommunity.microsoft.com/t5/microsoft-usb-blog/reasons-to-avoid-companion-controllers/ba-p/270710[Why disable these two?] +
Note: if a USB is no longer bootable after these two changes, temporarily turn them both back on.

. Windows Settings -> Gaming -> Enable "Game Mode"
** -> Graphics -> Change default graphics settings -> Enable "Hardware-accelerated GPU scheduling", "Variable refresh rate", and "Optimizations for windowed games"

. AMD CPUs: Install link:https://www.amd.com/en/support[AMD's Chipset Drivers]. +
Intel CPUs: Install link:https://www.intel.com/content/www/us/en/support/articles/000005533/software/chipset-software.html[Intel's Chipset Drivers].
** This will utilize their drivers instead of the generic drivers Microsoft provides, meaning better performance and lower DPC latency.

. Enable "User Account Control" if it's disabled; disabled will break some software, such as: link:https://eddie.website/[AirVPN's client].

. Kaspersky is the preferred anti-virus for consistently having these following reasons according to link:https://www.av-comparatives.org/vendors/kaspersky/[AV comparatives] and personal opinion:
** Very low performance impact.
** Top-tier detection ratios, with minimal false positives.
** Pricing is reasonable, unlike ESET.

TIP: Kaspersky is cheaper to buy from Amazon or other third-party markets that sell legitimate keys (not compromised accounts/keys).


=== Software

. link:https://www.speedguide.net/downloads.php[SG TCP Optimizer]
** Gets higher speeds and lower latency out of your network connection.

. link:https://winaerotweaker.com/[Winaero Tweaker]
** Extensive number of usability and visual tweaks.

. link:https://github.com/jbara2002/windows-defender-remover[Windows Defender Remover]
** Disables or removes Windows Defender.
*** Removing Windows Defender will break updates; you'd have to manually update through Microsoft's Update Catalog instead.

. link:https://www.oo-software.com/en/shutup10[ShutUp10]
** A privacy enhancer that doesn't break software.

. link:https://github.com/WereDev/Wu10Man[Wu10Man]
** Safely fully disables and enables Windows Update whenever, with no need to reboot for changes.

. link:https://dl.bitsum.com/files/processlassosetup64.exe[Process Lasso]
** Better thread scheduling (for specific CPUs) and the best power plan for gaming ("Bitsum Highest Performance").

TIP: If you ever removed Power Profiles, run `powercfg -restoredefaultschemes` before installing Process Lasso, otherwise "Bitsum Highest Performance" can't apply.