:experimental:
:imagesdir: imgs/
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Learning resources used
[%collapsible]
====

. https://archive.org/details/windows-internals-part1-7th/mode/2up
** https://github.com/zodiacon/WindowsInternals
. https://www.microsoftpressstore.com/store/windows-internals-part-2-9780135462409
** This can be viewed for free from link:https://en.wikipedia.org/wiki/Z-Library[Z-Library].

. https://github.com/MicrosoftDocs/windows-driver-docs/tree/staging/windows-driver-docs-pr
====

== Before continuing
. This mainly modifies registry keys, which just like Group Policy Editor, asks nicely for its modifications instead of enforcing it (as NTLite or MSMG Toolkit would).
** Disabling some features, especially about telemetry, are ignored on Windows versions that aren't Enterprise/Education/Server editions.
. It's assumed you have to reapply W11Boost after major Windows feature updates.
. Windows can at any time decide to revert single or multiple changes done by this script.

TIP: DuxOS is currently being worked on to make Windows 11 squeaky clean, and to be mostly a Windows 10 LTSC 2022 replica; the NTLite preset used and any other tweaks will be open-sourced, along with including a downloadable ISO for those that haven't purchased NTLite.

== Notes
* Does not overwrite user preferences that decrease privacy, except for those with a noticeable performance impact.
** It's assumed third-party tools do this job better, and not everyone wants to disable features that have privacy concerns.

* Gets rid of some of the auto-piloting that uses system resources, such as the link:https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.ApplicationCompatibility::AppCompatTurnOffEngine[Application Compatibility Engine].
** For ACE being off specifically, you would manually specify to run a legacy application in compatibility mode (likely for Windows XP).

* Fixes a few mistakes made by other optimizers.

* Only Windows 10 LTSC 2022 and newer are tested. 
** Older versions of Windows are worse in terms of stability, including Windows 7.

.Developer notes
[%collapsible]
====

* `reg.exe` is used instead of `reg` incase the system environment variables are misconfigured, same applies to anything else with `.exe` appended to its end.

* `reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\EXAMPLE" /v "Start" /t REG_DWORD /d 4 /f` is preferred over using `sc.exe config EXAMPLE start=disabled` since Windows rejects this request depending on the service.

* MMCSS (Multimedia Class Scheduler) doesn't exist in Windows 10 LTSC 2022 and newer.

* Registry keys usually don't self-regenerate themselves if their key doesn't exist.
** If the purpose is to revert back to defaults, manually set the default value instead.
====

== Requirements
. Windows has to be activated for some changes, use a license key, or use either link:https://github.com/abbodi1406/KMS_VL_ALL_AIO[abbodi1406's KMS_VL_ALL_AIO] or massgravel's link:https://github.com/massgravel/Microsoft-Activation-Scripts[Microsoft Activation Scripts].

. W11Boost.bat's `replace_windows_search=1` or `replace_windows11_interface=1` requires `winget`.
** For Windows 11, ensure `winget` is working, if not:
*** Open the Microsoft Store, then update "App Installer" through it.

** For Windows 10 LTSC 2019 or 2022, run in Command Prompt as Administrator to install `winget`:
*** `wsreset -i`
*** If the Microsoft store doesn't show up after this command is complete, reboot.
*** Open the Microsoft Store, then install "App Installer" through it.

** For Windows 10 LTSB 2016, install the Microsoft Store (provides the AppX installer, which provides `winget`) link:https://forums.mydigitallife.net/threads/guide-add-store-to-windows-10-enterprises-sku-ltsb-ltsc.70741/page-18#post-1388330[here].


== Instructions
. link:https://github.com/nermur/W11Boost/archive/refs/heads/master.zip[Download W11Boost], then extract it.
. Configure the options located inside `W11Boost.bat`, then run it as Administrator.

NOTE: Disable all anti-virus software before running `W11Boost.bat`.

== About "Optional extras"
* `W11_LTSC_2022.ps1`
** Uninstalls a lot of default apps to replicate what Windows 10 LTSC 2022 includes by default.
*** Exceptions: App Installer, Store Experience Host, Windows Store, Windows Terminal.

== Recommendations

=== Tweaks
. Enable the following options in your motherboard's BIOS:
** I/O APIC (IOAPIC 24-119 Entries)
** Above 4G Decoding
** Resizable BAR
*** NOTE: If Windows cannot boot (likely from using MBR instead of GPT), disable Resizable BAR.
** HPET (High Precision Event Timer)

. Disable the following options in your motherboard's BIOS:
** XHCI Hands Off
** USB Legacy
*** link:https://techcommunity.microsoft.com/t5/microsoft-usb-blog/reasons-to-avoid-companion-controllers/ba-p/270710[Why disable these two?] +
Note: if a USB is no longer bootable after these two changes, temporarily turn them both back on.

. Windows Settings -> Gaming -> Enable "Game Mode"
** -> Graphics -> Change default graphics settings -> Enable "Hardware-accelerated GPU scheduling", "Variable refresh rate", and "Optimizations for windowed games"

. Install all optional updates through Windows Update; it can include device drivers.

. Auto-detect and install link:https://www.amd.com/en/support[AMD's drivers]. +
Auto-detect and install link:https://www.intel.com/content/www/us/en/support/detect.html[Intel's drivers].
** This will utilize their drivers instead of the generic drivers Microsoft provides, meaning better performance and lower DPC latency.

. Enable "User Account Control" if it's disabled; disabled will break some software, such as: link:https://eddie.website/[AirVPN's client].

. Kaspersky is the preferred anti-virus for consistently having these following reasons according to link:https://www.av-comparatives.org/vendors/kaspersky-lab/[AV comparatives] and personal opinion:
** Very low performance impact.
** Top-tier detection ratios, with minimal false positives.
** Pricing is reasonable, unlike ESET.

TIP: Kaspersky is cheaper to buy from Amazon or other third-party markets that sell legitimate keys (not compromised accounts/keys).


=== Software

. link:https://www.speedguide.net/downloads.php[SG TCP Optimizer]
** Gets higher speeds and lower latency out of your network connection.

. link:https://winaerotweaker.com/[Winaero Tweaker]
** Extensive number of usability and visual tweaks.

. link:https://www.oo-software.com/en/shutup10[ShutUp10]
** A privacy enhancer that on its recommended settings doesn't break software.

. link:https://github.com/WereDev/Wu10Man[Wu10Man]
** Can fully and safely disable or enable Windows updates without rebooting.

. link:https://dl.bitsum.com/files/processlassosetup64.exe[Process Lasso]
** Better thread scheduling (for specific CPUs) and the best power plan for gaming ("Bitsum Highest Performance").

INFO: If you ever removed Power Profiles, run `powercfg -restoredefaultschemes` before installing Process Lasso, otherwise "Bitsum Highest Performance" can't apply.