@echo on
set PARMS=--exact --silent --accept-source-agreements

winget.exe uninstall Clipchamp.Clipchamp_yxz26nhyzhsrt %PARMS%
winget.exe uninstall Disney.37853FC22B2CE_6rarf9sa4v8jt %PARMS%
winget.exe uninstall Microsoft.549981C3F5F10_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.BingNews_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.BingWeather_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.GamingApp_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.GetHelp_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.Getstarted_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.OneDrive %PARMS%
winget.exe uninstall Microsoft.OneDriveSync_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.Todos_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.Windows.Photos_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.WindowsAlarms_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.WindowsCamera_8wekyb3d8bbwe %PARMS%
winget.exe uninstall microsoft.windowscommunicationsapps_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.WindowsMaps_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.Xbox.TCUI_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.XboxGameOverlay_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.XboxGamingOverlay_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.XboxIdentityProvider_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.YourPhone_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.ZuneMusic_8wekyb3d8bbwe %PARMS%
winget.exe uninstall Microsoft.ZuneVideo_8wekyb3d8bbwe %PARMS%
winget.exe uninstall MicrosoftCorporationII.QuickAssist_8wekyb3d8bbwe %PARMS%
winget.exe uninstall MicrosoftTeams_8wekyb3d8bbwe %PARMS%
winget.exe uninstall MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy %PARMS%
winget.exe uninstall SpotifyAB.SpotifyMusic_zpdnekdrzrea0 %PARMS%
